version: '3.9'
services:
  web:
    build: ./web
    image: akitsune/akiled-web
    env_file:
      - .env
    ports:
      - ${HTTP_HOST_PORT}:80
    volumes:
      - ./web/configs/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./web/configs/nginx.mimetypes.conf:/etc/nginx/nginx.mimetypes.conf
      - ./web/include:/usr/share/nginx/include:ro
      - ./logs/nginx:/usr/share/nginx/logs
      - ./data/camera/cam:/usr/share/nginx/html/swfs/newfoto/camera
      - ./data/camera/thumb:/usr/share/nginx/html/swfs/thumbnail
    command: ["dockerize",
              "-template", "/etc/nginx/nginx.conf.template:/etc/nginx/nginx.conf",
              "-template", "/usr/share/nginx/html/system/brain-config.php.template:/usr/share/nginx/html/system/brain-config.php",
              "-template", "/usr/share/nginx/html/swfs/gamedata/vars.txt.template:/usr/share/nginx/html/swfs/gamedata/vars.txt",
              "-template", "/usr/share/nginx/html/swfs/nitro/ui-config.json.template:/usr/share/nginx/html/swfs/nitro/ui-config.json",
              "-template", "/usr/share/nginx/html/swfs/nitro/renderer-config.json.template:/usr/share/nginx/html/swfs/nitro/renderer-config.json",
              "/usr/local/sbin/runsvdir-init"]
  db:
    image: mariadb:10.4.21
    ports:
      - ${MARIADB_HOST_PORT}:3306
    volumes:
      - ./data/MariaDB:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --sql_mode=''
    environment:
      MARIADB_ROOT_PASSWORD: ''
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/Redis:/data
  game:
    build: ./gameEmu
    image: akitsune/akiled-game
    env_file:
      - .env
    ports:
      - 527:527
      - 30001:30001
      - 30000:30000
    volumes:
      - ./gameEmu/templates/configuration.ini.template:/app/Settings/configuration.ini.template:ro
      - ./logs/game:/app/logs
    command: ["dockerize",
              "-template", "/app/Settings/configuration.ini.template:/app/Settings/configuration.ini",
              "dotnet", "AkiledEmulator.dll"]
  websockify:
    build: ./websockify
    image: akitsune/akiled-websockets
    ports:
      - 2096:2096
    command: ["node", "websockify.js", "0.0.0.0:2096", "game:30000"]
  # -- BEGIN PhpMyAdmin
  # If this is uncommented, then you will get a PHPMyAdmin page on the port specified in .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 10G
    restart: always
    ports:
      - ${PMA_PORT}:80
  # -- END PhpMyAdmin
